### ISSUE TITLE
Returning HTML as variable gives a warning: unique "key" prop

### ISSUE THREAD

**Issue by kladnik** [formatjs/formatjs#1549]
Every time I return HTML as a variable I get the following warning:
`Warning: Each child in a list should have a unique "key" prop.`

### Example

```
"test-translation": "test1{br}test2" <--- Example
const { formatMessage: f } = useIntl();

<div className="gray">{f({ id: 'test-translation' }, { br: <br /> })}</div> <--- Warning here
<div className="gray">{f({ id: 'test-translation' }, { br: 'test' })}</div> <--- No warning here
```

There is no reason to add `key` to each HTML, this should be handled by the package.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.9.2 |
|      `npm ls react` | 16.12.0 |
|     `npm --version` | 6.13.0 |
|    `node --version` | 12.13.0 |

| OS   | Version |
| ---- | ------- |
| Ubuntu | 18.04.3 |

| Browser | Version |
| ------- | ------- |
| Chrome | 79.0.3945.88 |

**Comment by omkar-joshi** [comment]
I'd like to help with this

**Comment by kladnik** [comment]
Closing the issue, since it was fixed with #1550 in version 3.11.0.
Thank you @mallchel for solving it.

**Comment by kladnik** [comment]
I just updated to 4.5.0 and the issue is back again. Could you take another look?

**Comment by mallchel** [comment]
> I just updated to 4.5.0 and the issue is back again. Could you take another look @mallchel ?

Hm, challenge accepted :)

**Comment by longlho** [comment]
it's still there under `wrapRichTextChunksInFragment` config

**Comment by kladnik** [comment]
Hmm, how come I am still receiving this errors then? I made a clean build with version `4.5.0` and the errors are there and when I use `3.11.0` they disappear. What else could be the issue?

**Comment by kladnik** [comment]
An example of error location:
```strong: msg => <strong>{msg}</strong>```

Error:
`Warning: Each child in a list should have a unique "key" prop.`

Placing a random key in `<strong>` removes the error.

**Comment by longlho** [comment]
Did you set `wrapRichTextChunksInFragment: true` in your `Provider`?

**Comment by kladnik** [comment]
Yes this is my provider:
```
<IntlProvider
            locale={locale}
            messages={{messages}}
            wrapRichTextChunksInFragment={true}
>
```
Am I missing something?

**Comment by mallchel** [comment]
> Yes, this is my provider:
> 
> ```
> <IntlProvider
>             locale={locale}
>             messages={{messages}}
>             wrapRichTextChunksInFragment={true}
> >
> ```
> 
> Am I missing something?

I reproduced your situation. This seems to work as expected. https://codesandbox.io/s/dank-leaf-zn9vt?file=/src/App.js

**Comment by kladnik** [comment]
In the example you posted I can see the key error and you're saying it's expected? 
But what I noticed right now is the error only shows on page load.

**Comment by jellevanwezel** [comment]
Same problem here with 4.x.x, with 3.11.0 its gone.

**Comment by kladnik** [comment]
So it's not just me. Could we maybe reopen this, @longlho ?

**Comment by longlho** [comment]
kk ill reopen it and investigate

**Comment by mallchel** [comment]
> In the example you posted I can see the key error and you're saying it's expected?
> But what I noticed right now is the error only shows on page load.

Sorry, I missed it. Because wrapRichTextChunksInFragment is always undefined :)

**Comment by mallchel** [comment]
@longlho Why is the config processing with hands here?
![image](https://user-images.githubusercontent.com/21968689/80273090-07caa380-86d8-11ea-883e-eb1e566a49de.png)

**Comment by longlho** [comment]
We do allow IntlProvider to inherit from another one: https://github.com/formatjs/react-intl/blob/master/test/unit/components/provider.tsx#L195 and only some configs are safe to be inherited

**Comment by eXaminator** [comment]
Has this been released? I'm on the latest react-intl version but still get this error. There have been multiple releases since, but I didn't see this fix in the changelogs.

**Comment by kladnik** [comment]
What is the status with this? It's been almost two months since this issue is closed, but I still don't see it in the newest version.

**Comment by longlho** [comment]
We fixed 1 instance of this but you're prob looking for #1623

**Comment by kladnik** [comment]
> What is the status with this? It's been almost two months since this issue is closed, but I still don't see it in the newest version.

Asking again, since I am on the newest version and still seeing the warnings ...

**Comment by longlho** [comment]
did u turn on https://formatjs.io/docs/react-intl/components#wraprichtextchunksinfragment ?

**Comment by kladnik** [comment]
> did u turn on https://formatjs.io/docs/react-intl/components#wraprichtextchunksinfragment ?

No I did not. Thanks, the warning are gone now!
