### ISSUE TITLE
react-intl requires react 16.3.0 but uses React.memo which is available only on 16.6.0

### ISSUE THREAD

**Issue by guilhermesalerno** [formatjs/formatjs#3587]
## Which package?
react-intl

## Describe the bug
react-intl requires react as a [peer dependency](https://github.com/formatjs/formatjs/blob/main/packages/react-intl/package.json#L143) at version 16.3.0 however it uses [React.memo](https://github.com/formatjs/formatjs/blame/567a131a910e0bc2584cc031235b8987d91d815a/packages/react-intl/src/components/message.tsx#L61) which is only available on [React 16.6.0](https://reactjs.org/blog/2018/10/23/react-v-16-6.html)

## To Reproduce
A simple application with react-intl@latest and react@16.3.0 will throw an error `memo is not a function`

### Codesandbox URL

https://codesandbox.io/s/format-js-forked-ew63by

### Reproducible Steps/Repo

1. Just try to execute the application and you will see the error during the startup

## Expected behavior
The application loads without errors. Probably the fix here would be to change package.json to require react @16.6.0

## Desktop (please complete the following information):

- N/A

## Smartphone (please complete the following information):

- N/A

**Comment by longlho** [comment]
fixed in latest

**Comment by guilhermesalerno** [comment]
Sorry, but I think the problem persists on the latest version. I updated the codesandbox to use `react-intl@6.0.1` and the same error occurs if you try to use `react@16.3.0` because `memo` is still used inside `react-intl`.
 I opened a PR that changes the peerDependency requirement for React to 16.6.0 which is when `memo` was introduced: https://github.com/formatjs/formatjs/pull/3612 which would make the dependency tree more accurate.
