### ISSUE TITLE
React-intl typescript rich text formatting: documentation vs. type definitions

### ISSUE THREAD

**Issue by Phibedy** [formatjs/formatjs#3633]
## Which package?
* version: https://registry.yarnpkg.com/@formatjs/cli/-/cli-5.0.1.tgz#52d0316df059ca3b631ee88239e347f2e954558b
* react-intl: https://registry.yarnpkg.com/react-intl/-/react-intl-5.25.1.tgz#68a73aefc485c9bf70062381ae7f6f4791680879

What is the correct way to do rich text formatting?
Here it says, that it should work like this: https://formatjs.io/docs/react-intl/api/#usage (second eric example)

```
  return intl.formatMessage({defaultMessage:"a <b>b</b> c"}, {
    b: str => <b>{str}</b>,
  })
```

but the typescript type does not allow a function to be passed inside values. It is currently just `key: ReactNode`

Error:
```
No overload matches this call.
  Overload 1 of 2, '(descriptor: MessageDescriptor, values?: Record<string, PrimitiveType | FormatXMLElementFn<string, string>> | undefined, opts?: Options | undefined): string', gave the following error.
    Type '(str: string[]) => Element' is not assignable to type 'PrimitiveType | FormatXMLElementFn<string, string>'.
      Type '(str: string[]) => Element' is not assignable to type 'FormatXMLElementFn<string, string>'.
        Type 'Element' is not assignable to type 'string'.
  Overload 2 of 2, '(descriptor: MessageDescriptor, values?: Record<string, string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | ... 5 more ... | undefined> | undefined, opts?: Options | undefined): ReactNode', gave the following error.
    Type '(str: string[]) => Element' is not assignable to type 'string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal | Date | FormatXMLElementFn<...> | null | undefined'.
      Type '(str: string[]) => Element' is not assignable to type 'FormatXMLElementFn<ReactNode, ReactNode>'.
        Types of parameters 'str' and 'parts' are incompatible.
          Type 'ReactNode[]' is not assignable to type 'string[]'.
            Type 'ReactNode' is not assignable to type 'string'.
              Type 'undefined' is not assignable to type 'string'.ts(2769)
```

**Comment by longlho** [comment]
what's your version of react?

**Comment by Phibedy** [comment]
@longlho I am currently using react 17.0.2

**Comment by tm1000** [comment]
This was resolved 14 days ago. See: https://github.com/formatjs/formatjs/commit/2567b932c5d18b097a43842563046c20ce0c49f1#diff-2bcb6471a8482e09da6a7c26e41bbc3eec79ff897e00b7f21375d6a8234a73d6

[react-intl@6.0.3](https://github.com/formatjs/formatjs/releases/tag/react-intl%406.0.3)

**Comment by mrcrazylee** [comment]
Same issue here. Using `react-intl` on v6.0.4 does not resolve the issue. I must note that I have react version 18.1.0 running.

**Comment by tm1000** [comment]
It did fix it for me and I am on the same react version which is the only reason I posted it was fixed.

**Comment by longlho** [comment]
is there a repro codesandbox?

**Comment by mrcrazylee** [comment]
@longlho @tm1000 You're right. While creating a reproduction in codesandbox I noticed that we needed to type values liike this:

```tsx
<FormatMessage
    defaultMessage="This is <b>{name}</b>!"
    id="some-id"
    values={{
        name: 'John'
        b: (chunks: string[]) => <strong>{chunks}</strong>
    }}
/>
```

This was probably taken some time ago from another example. The solutions is to remove the typing and just use the inferred type like so:

```tsx
<FormatMessage
    defaultMessage="This is <b>{name}</b>!"
    id="some-id"
    values={{
        name: 'John'
        b: chunks => <strong>{chunks}</strong>
    }}
/>
```

This works perfectly. Typing chunks as a `string[]` was conflicting with the types from formatJS itself. For me at least this is no longer a problem, just need to remove all the extra typing where we use values. My apologies for the inconvenience. I came here because of the exact same error message as stated in this issue, but in my case it was caused by a mismatch in typing. Thanks for the help gents!

**Comment by Phibedy** [comment]
Works :+1:

**Comment by maxgertzen** [comment]
Hey, I'm using react-intl version 6.0.5 with react 18.2.
I'm getting the same error as described while using intl.formatMessage (of type IntlShape).

`Type '(item: string[]) => Element' is not assignable to type 'PrimitiveType | FormatXMLElementFn<string, string>'.`

Note that I use the object which `useIntl()` returns.

![image](https://user-images.githubusercontent.com/34470211/178464994-02a39e2c-53d5-4a1f-8f22-4ce7834a0f46.png)

**Comment by jsaulsberry-cvet** [comment]
Also seeing the same issue @maxgertzen

**Comment by marcnewport** [comment]
I'm seeing the same issue as @maxgertzen (react@18.2.0, react-intl@6.1.1)

I've found that typing the `chunks` prop as `ReactNode` stopped typescript from complaining. eg.

```
const message = intl.formatMessage('Message with <a>link</a>', {
    a: (chunks: ReactNode) => (
      <a
        href={someHref}
        target="_blank"
      >
        {chunks}
      </a>
    )
})
```

**Comment by Jonur** [comment]
Hi everyone, I think the issue still persists, or I am doing something very wrong. I am on React@18.0.2 and react-intl@6.2.10. I am following @marcnewport and @maxgertzen comments.

For the following:
```javascript
import { useIntl } from 'react-intl';

// ...

const { formatMessage } = useIntl();

// ...

formatMessage(
      {
        id: 'app.description',
      },
      { li: (c: React.ReactNode) => <li>{c}</li>, b: (c: React.ReactNode) => <strong>{c}</strong> }
    );
  };
```
When I type `c` as `React.ReactNode` or `ReactNode`, TS complains that:
```
Type 'string | boolean | (string | boolean)[]' is not assignable to type 'string'.
  Type 'boolean' is not assignable to type 'string'.ts(2322)
```

When I type `c` as `string[]`, TS complains that:
```
No overload matches this call.
  Overload 1 of 2, '(descriptor: MessageDescriptor, values?: Record<string, PrimitiveType | FormatXMLElementFn<string, string>> | undefined, opts?: Options | undefined): string', gave the following error.
    Type '(c: string[]) => boolean' is not assignable to type 'PrimitiveType | FormatXMLElementFn<string, string>'.
      Type '(c: string[]) => boolean' is not assignable to type 'FormatXMLElementFn<string, string>'.
        Type 'boolean' is not assignable to type 'string'.
  Overload 2 of 2, '(descriptor: MessageDescriptor, values?: Record<string, PrimitiveType | FormatXMLElementFn<boolean, string | boolean | (string | boolean)[]>> | undefined, opts?: Options | undefined): string | ... 1 more ... | (string | boolean)[]', gave the following error.
    Type '(c: string[]) => boolean' is not assignable to type 'PrimitiveType | FormatXMLElementFn<boolean, string | boolean | (string | boolean)[]>'.
      Type '(c: string[]) => boolean' is not assignable to type 'FormatXMLElementFn<boolean, string | boolean | (string | boolean)[]>'.
        Types of parameters 'c' and 'parts' are incompatible.
          Type '(string | boolean)[]' is not assignable to type 'string[]'.
            Type 'string | boolean' is not assignable to type 'string'.
              Type 'boolean' is not assignable to type 'string'.
```

The values work correctly, when I use the `<FormattedMessage />` component. For example,
```javascript
<FormattedMessage
  id="app.description"
  values={{ li: (c) => <li>{c}</li>, b: (c) => <strong>{c}</strong> }}
/>
```

I have ensured that React is imported in the file. I have tried on both `.ts` and `.tsx` files.

Does anyone know why this happens, or what am I doing wrong? I have tried everything I've seen online - I might have missed something, and also restarted VSCode and TS server just in case.

Strangely, with ignoring TS by adding a `@ts-ignore` above the `formatMessage(...)` call, the code works fine. But I do not understand why we have a type issue.

**Comment by maxgertzen** [comment]
> Hi everyone, I think the issue still persists, or I am doing something very wrong. I am on React@18.0.2 and react-intl@6.2.10. I am following @marcnewport and @maxgertzen comments.
> 
> For the following:
> 
> ```js
> import { useIntl } from 'react-intl';
> 
> // ...
> 
> const { formatMessage } = useIntl();
> 
> // ...
> 
> formatMessage(
>       {
>         id: 'app.description',
>       },
>       { li: (c: React.ReactNode) => <li>{c}</li>, b: (c: React.ReactNode) => <strong>{c}</strong> }
>     );
>   };
> ```
> 
> When I type `c` as `React.ReactNode` or `ReactNode`, TS complains that:
> 
> ```
> Type 'string | boolean | (string | boolean)[]' is not assignable to type 'string'.
>   Type 'boolean' is not assignable to type 'string'.ts(2322)
> ```
> 
> When I type `c` as `string[]`, TS complains that:
> 
> ```
> No overload matches this call.
>   Overload 1 of 2, '(descriptor: MessageDescriptor, values?: Record<string, PrimitiveType | FormatXMLElementFn<string, string>> | undefined, opts?: Options | undefined): string', gave the following error.
>     Type '(c: string[]) => boolean' is not assignable to type 'PrimitiveType | FormatXMLElementFn<string, string>'.
>       Type '(c: string[]) => boolean' is not assignable to type 'FormatXMLElementFn<string, string>'.
>         Type 'boolean' is not assignable to type 'string'.
>   Overload 2 of 2, '(descriptor: MessageDescriptor, values?: Record<string, PrimitiveType | FormatXMLElementFn<boolean, string | boolean | (string | boolean)[]>> | undefined, opts?: Options | undefined): string | ... 1 more ... | (string | boolean)[]', gave the following error.
>     Type '(c: string[]) => boolean' is not assignable to type 'PrimitiveType | FormatXMLElementFn<boolean, string | boolean | (string | boolean)[]>'.
>       Type '(c: string[]) => boolean' is not assignable to type 'FormatXMLElementFn<boolean, string | boolean | (string | boolean)[]>'.
>         Types of parameters 'c' and 'parts' are incompatible.
>           Type '(string | boolean)[]' is not assignable to type 'string[]'.
>             Type 'string | boolean' is not assignable to type 'string'.
>               Type 'boolean' is not assignable to type 'string'.
> ```
> 
> The values work correctly, when I use the `<FormattedMessage />` component. For example,
> 
> ```js
> <FormattedMessage
>   id="app.description"
>   values={{ li: (c) => <li>{c}</li>, b: (c) => <strong>{c}</strong> }}
> />
> ```
> 
> I have ensured that React is imported in the file. I have tried on both `.ts` and `.tsx` files.
> 
> Does anyone know why this happens, or what am I doing wrong? I have tried everything I've seen online - I might have missed something, and also restarted VSCode and TS server just in case.
> 
> Strangely, with ignoring TS by adding a `@ts-ignore` above the `formatMessage(...)` call, the code works fine. But I do not understand why we have a type issue.

I would try removing the type all together, this what solved our issue with that. I'm almost certain that from the latest versions, the type is inferred - meaning you can do just `li: (chunks) => <li>{chunks}</li>`

**Comment by Jonur** [comment]
@maxgertzen Yes, I have removed chunks' type. However, it still complains and I am just adding `@ts-ignore`. The error I am getting without any types is as if I typed it a `string[]`.

```
No overload matches this call.
  Overload 2 of 2, '(descriptor: MessageDescriptor, values?: Record<string, PrimitiveType | Element | FormatXMLElementFn<Element, string | Element | (string | Element)[]>> | undefined, opts?: Options | undefined): string | ... 1 more ... | (string | Element)[]', gave the following error.
    Type '(c: string[]) => Element' is not assignable to type 'PrimitiveType | Element | FormatXMLElementFn<Element, string | Element | (string | Element)[]>'.
      Type '(c: string[]) => Element' is not assignable to type 'FormatXMLElementFn<Element, string | Element | (string | Element)[]>'.
        Types of parameters 'c' and 'parts' are incompatible.
          Type '(string | Element)[]' is not assignable to type 'string[]'.
            Type 'string | Element' is not assignable to type 'string'.
              Type 'Element' is not assignable to type 'string'.
  Overload 2 of 2, '(descriptor: MessageDescriptor, values?: Record<string, PrimitiveType | Element | FormatXMLElementFn<Element, string | Element | (string | Element)[]>> | undefined, opts?: Options | undefined): string | ... 1 more ... | (string | Element)[]', gave the following error.
    Type '(c: string[]) => Element' is not assignable to type 'PrimitiveType | Element | FormatXMLElementFn<Element, string | Element | (string | Element)[]>'.
      Type '(c: string[]) => Element' is not assignable to type 'FormatXMLElementFn<Element, string | Element | (string | Element)[]>'.
        Types of parameters 'c' and 'parts' are incompatible.
          Type '(string | Element)[]' is not assignable to type 'string[]'.ts(2769)
```

**Comment by ezorita** [comment]
This is still failing in react 18.2.0 and react-intl 6.5.0:
![image](https://github.com/formatjs/formatjs/assets/3889419/189f8849-3eec-4a9b-9f7f-09fba5d821aa)

any ideas?

**Comment by ezorita** [comment]
The type error is still there in React 18.2.0 and react-intl 6.5.0

![image](https://github.com/formatjs/formatjs/assets/3889419/9c327a69-658f-4ac1-bc49-7d34c93503de)


Any ideas?

**Comment by iratner** [comment]
I was having the same issues, and returning a template literal in the callback fixes the issue.   For example:
```typescript
const translationStyles = {
  bold: (chunks: string[]) => {
    return `<span
        style={{
          color: palette.base.brand,
          fontWeight: 700,
          fontStyle: 'italic',
        }}
      >
        ${chunks}
      </span>`
  },
}
```

```shell
"react-intl": "^6.1.1",
"react": "^18.2.0",
```

**Comment by nielsfilmer** [comment]
Returning a template literal results in the HTML just showing as text for me. Is there a real solution for this problem? I'm still adding // @ts-ignore everywhere now.
