### ISSUE TITLE
Type issue with TypeScript 4.9

### ISSUE THREAD

**Issue by nstepien** [formatjs/formatjs#3910]
## Which package?

`@formatjs/intl`

## Describe the bug

These type issues started appearing after I upgraded to TypeScript 4.9.

```
node_modules/@formatjs/intl/src/types.d.ts:21:26 - error TS2339: Property 'ids' does not exist on type 'Message'.

21 } ? FormatjsIntl.Message['ids'] : string;
                            ~~~~~

node_modules/@formatjs/intl/src/types.d.ts:24:29 - error TS2339: Property 'locale' does not exist on type 'IntlConfig'.

24 } ? FormatjsIntl.IntlConfig['locale'] : string;
```

### Codesandbox URL

Please include a codesandbox URL if possible

### Reproducible Steps/Repo

1. Install [TypeScript 4.9.3](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/)
2. run `tsc`

## Expected behavior

No type issues.

## Desktop (please complete the following information):

- OS: [e.g. iOS] Windows 11
- Browser [e.g. chrome, safari] n/a
- Version [e.g. 22] `@formatjs/intl@2.5.1`

## Smartphone (please complete the following information):

- Device: [e.g. iPhone6] n/a
- OS: [e.g. iOS8.1] n/a
- Browser [e.g. stock browser, safari] n/a
- Version [e.g. 22] n/a

## Additional context

I did not have this issue with TS 4.8.

**Comment by cungminh2710** [comment]
Duplicate of #3905 i believe

**Comment by zmagauina-fn** [comment]
I'm also having this issue, TS 4.9 doesn't seem to like this syntax:
```
declare type MessageIds = FormatjsIntl.Message extends {
    ids: string;
} ? FormatjsIntl.Message['ids'] : string;
declare type Locale = FormatjsIntl.IntlConfig extends {
    locale: string;
} ? FormatjsIntl.IntlConfig['locale'] : string;
```

**Comment by nstepien** [comment]
@pyrocat101 I've installed the updated packages, and `@formatjs/intl@2.6.0` still has the same type issue:
```
> tsc

node_modules/@formatjs/intl/src/types.d.ts:22:14 - error TS2339: Property 'ids' does not exist on type 'Message'.

22 } ? _Message['ids'] : string;
                ~~~~~

node_modules/@formatjs/intl/src/types.d.ts:26:17 - error TS2339: Property 'locale' does not exist on type 'IntlConfig'.

26 } ? _IntlConfig['locale'] : string;
                   ~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@formatjs/intl/src/types.d.ts:22
```

FWIW here's my tsconfig:
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "pretty": true,
    "strict": true,
    "target": "esnext",
    "types": ["jest", "@testing-library/jest-dom"]
  }
}

```

**Comment by cungminh2710** [comment]
+1 I still face the issue `error TS2339: Property 'ids' does not exist on type 'Message'.` 
![image](https://user-images.githubusercontent.com/8063319/204667919-1e4172eb-a51d-4ff5-8190-ab54944a42a2.png)

**Comment by aradzie** [comment]
This issue still exists in the newest @formatjs/intl-2.6.0

**Comment by pyrocat101** [comment]
Ah sorry. This should be actually fixed by #3919. I will do a release.

**Comment by nstepien** [comment]
@pyrocat101 Thank you very much for the fix and release, no more type issues here 👍

**Comment by RunMarathon** [comment]
@pyrocat101 Issue still exists in package "@formatjs/intl-locale": "^3.0.11"

Can this fixed here, too? Thank you.

**Comment by midorizemi** [comment]
@pyrocat101 Hi, Thank you for your help. I've recently encountered an issue with a similar error. Even though I've installed @formatjs/intl-2.6.3, the problem still persists in my formatjs/intl-2.6.3 environment using TypeScript 4.9.4.


![スクリーンショット 2023-01-16 15 57 13](https://user-images.githubusercontent.com/927671/212616533-e37b0689-68bf-40d8-9bb9-ffb5aea7ca99.png)
