### ISSUE TITLE
Documentation website – live editor not working

### ISSUE THREAD

**Issue by jufemaiz** [formatjs/formatjs#4898]
## Which package?

Docs, more specifically the docs website.

## Describe the bug

Docs website makes use of "live editor" areas in the documentation allowing people to edit the content and see the feedback immediately. This is not currently working in Chrome (v119.0.6045.105) / Brave (v1.60.110 – Chromium: v119.0.6045.105) / Safari (v17.2) on MacOS (Sonoma v14.2 Beta (23C5041e)).

Tried multiple connectivity paths.

### Codesandbox URL

Please include a codesandbox URL if possible

### Reproducible Steps/Repo

1. Go to https://formatjs.github.io/docs/react-intl/api#usage *or* https://formatjs.github.io/docs/intl/#usage
2. Go to a live editor box
3. Notice that there was no output below
4. Amend the contents in the live editor box
5. See that there is not change, that is there is still no output

## Expected behavior

The live output should reflect what one expects from the relevant function call.

## Screenshots

<img width="980" alt="Image" src="https://github.com/user-attachments/assets/0e09bed1-6553-4597-bb3a-bcb8b033582b" />

<img width="981" alt="Image" src="https://github.com/user-attachments/assets/c452db8e-d058-432b-b52d-f853455b03e4" />

## Desktop (please complete the following information):

- Device: Laptop
- OS: MacOS (v14.3.1)
- Browsers
    - Brave (Version 1.75.180 Chromium: 133.0.6943.126 (Official Build) (x86_64))
    - Safari (Version 18.3) on MacOS (v14.3.1)

## Related

Previously raised https://github.com/formatjs/formatjs/issues/4259.

**Comment by jufemaiz** [comment]
Yeah, nah, still not working.

**Comment by jufemaiz** [comment]
Yeah, nah, still not working.

**Comment by longlho** [comment]
sry this should have been fixed already

**Comment by jufemaiz** [comment]
@longlho I'm still not seeing it fixed in the live implementation.

https://www.loom.com/share/e49cd4c0856b47bca877f6be119eb73f

**Comment by longlho** [comment]
Thanks for reporting! Should be fixed in https://github.com/formatjs/formatjs/pull/5819

**Comment by jufemaiz** [comment]
Thanks! Working for https://formatjs.github.io/docs/react-intl/api/#usage

However, https://formatjs.github.io/docs/intl/#usage is still showing issues. Now indicating syntax error.

As an example:

```
SyntaxError: Unexpected token (1:32)
```

<img width="919" height="458" alt="Image" src="https://github.com/user-attachments/assets/50e104d7-f9ca-4712-9c37-23ef6ee6f135" />
